### ISSUE TITLE
Integration with Webhooks

### ISSUE THREAD

**Issue by adityasanehi** [Architrixs/myntra_scraper.py#1]
Hey, could this be connected to a slack/zapier/discord webhook to be updated of changes in the elements?

**Comment by adityasanehi** [comment]
I’m looking for something that will monitor some products availability for me and this scraper works very fine for links. I was wondering if it could be done. Would seem useful for Myntra days and wish lists.

**Comment by Architrixs** [comment]
I haven't worked with any webhook, so I wouldn't know all about this, But from what I know using the generated data as a payload and loading it with a requests.post() function will do the work, of course, you'll need the slack/discord webhook URL or something for that.
I am not sure about the other way around.

**Comment by Architrixs** [comment]
Also, Thanks for taking a look at this, let me know how this works out for you, I'll help.
